name: CI

on: [push, pull_request]

jobs:
  lint:
    name: Lint with Ruff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chartboost/ruff-action@v1

  test:
    name: Run Django Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Tests and Generate HTML Coverage Report
        run: |
          coverage run manage.py test
          coverage html  # Génère un rapport HTML

      - name: Upload Coverage HTML Report
        uses: actions/upload-artifact@v2
        with:
          name: html-coverage-report
          path: htmlcov/
