name: CI

on: [push, pull_request]

jobs:
  lint:
    name: Lint with Ruff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chartboost/ruff-action@v1

  test:
    name: Run Unittests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Run unittest
        run: |
          python -m unittest discover
